config/routes.rb
Rails.application.routes.draw do
  
  root 'workouts#index'
  
  devise_for :users
  
  resources :users, only: [:show]
  
  resources :workouts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :workouts
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_workout, only: [:show, :edit, :update, :destroy]
  
  def index
    @workouts = current_user.workouts
  end
  
  def show
  end
  
  def new
    @workout = current_user.workouts.build
  end
  
  def create
    @workout = current_user.workouts.build(workout_params)
    if @workout.save
      redirect_to @workout, notice: "Saved."
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end
  
  private
  
  def workout_params
    params.require(:workout).permit(:date, :workout, :content, :length)
  end
  
  def find_workout
    @workout = Workout.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="alert devise"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jimmy's Workout</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    <% flash.each do |key, value| %>
      <% alert_class = case key
        when :notice then "success"
        when :alert then "danger"
        else key
        end %>
        <%= content_tag :div, class: "alert alert-info" do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= value %>
        <% end %>
    <% end %>
    
    <%= render 'shared/navbar' %>
    
    <div class="container content">
      <%= yield %>  
    </div> 
  </body>
</html>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top" style="margin-bottom: 0px">
  <div class="container">
    <div class="navbar-header">
       
      <%= link_to "Jimmy's Workout", root_path, class: "navbar-brand" %>
      
    </div> 
    <% if (user_signed_in?) %>
    <ul class="nav navbar-nav navbar-right">       
      <li><%= link_to "New Workout", new_workout_path %></li>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    </ul>
    <% end %>
  </div>
</nav>

app/views/workouts/_form.html.erb
<%= simple_form_for(@workout) do |f| %>
  <%= f.input :date, label: "Date" %>
  <%= f.input :workout, label: "What was the focus of today's workout?", input_html: { class: "form-control" } %>
  <%= f.input :content, label: "Add your comments about the workout here.", input_html: { class: "form-control" } %>
  <%= f.input :length, label: "How long was the workout?", input_html: { class: "form-control" } %>
  <br/>
  <%= f.button :submit, { class: "btn btn-save" } %>
<% end %>

app/views/workouts/edit.html.erb
<h1>Edit Workout</h1>

<br>

<%= render 'form' %>

<br>

<%= link_to "Cancel", root_path %>

app/views/workouts/index.html.erb
<div class="col-md-6">
  <div id="index_workouts">
    <% @workouts.each do |workout| %>
      <div class="panel panel-default index">
        <div class="container">
          <h4>
            <%= link_to workout.date.strftime("%A %B %d"), workout %>
          </h4>
          <p>
            <span>Workout:</span>
            <%= workout.workout %>
          </p>
        </div> 
      </div>
    <% end %>     
  </div>  
</div>

app/views/workouts/new.html.erb
<h4>New Workout</h4>

<br>

<%= render 'form' %>

<br>

<%= link_to "Cancel", root_path %>

app/views/workouts/show.html.erb
<div id="workout">
  <p>
    <%= @workout.date %>
  </p>
  <h3>
    <strong><%= @workout.workout %></strong>
  </h3>
  <p>
    <%= @workout.content %>
  </p>
  <p>
    <%= @workout.length %>
  </p>
</div>
<div id="exercises">
  
</div>

<br>

<%= link_to "Back", root_path %>&nbsp;
<%= link_to "Edit", edit_workout_path(@workout) %>&nbsp;
<%= link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "Are you sure?" } %>